name: nino
version: "1.3.1"
grade: stable
base: core18
summary: nino
description: |
    Nino is an internet speed monitor with a simple appearance.
    Small window application features.
    Alert when no internet connection is available.
    Many color theme choices are available.
    Lock position on the desktop.
    Save the position of the widget.
    The choice is always above the screen or below.
confinement: strict
parts:
  nino:
    after: [desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/torikulhabib/nino.git
    override-build: |
        snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/128x128/apps/com.github.torikulhabib.nino.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.torikulhabib.nino.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libgranite-dev
        - libgtop2-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
        - libgtop-2.0-11
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  nino:
    command: desktop-launch $SNAP/usr/bin/com.github.torikulhabib.nino
    desktop: usr/share/applications/com.github.torikulhabib.nino.desktop
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    slots: [ dbus-nino ]
slots:
  dbus-nino:
    interface: dbus
    bus: session
    name: com.github.torikulhabib.nino
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
